### ISSUE TITLE
Error while running the pipeline of Aachen

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#118]
I get this error in the match_features.main() function of the Aachen pipeline:

[11/04/2021 08:57:35 INFO] Matching local features with configuration:
{'model': {'name': 'superglue',
           'sinkhorn_iterations': 50,
           'weights': 'outdoor'},
 'output': 'matches-superglue'}
Loaded SuperGlue model ("outdoor" weights)
  0%|                                                                                                                                                                            | 0/85515 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "pipeline_Aachen.py", line 38, in <module>
    sfm_match_path = match_features.main(matcher_conf, sfm_pairs, feature_conf['output'], outputs)
  File "/home/ubuntu/Hierarchical-Localization/hloc/match_features.py", line 83, in main
    match_from_paths(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/Hierarchical-Localization/hloc/match_features.py", line 147, in match_from_paths
    data['image1'] = torch.empty((1,)+tuple(grp['image_size'])[::-1])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ubuntu/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 305, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'image_size' doesn't exist)"

**Comment by hiXiaoYU** [comment]
hi,Did you solve this problem and how it was solved? thanks!

**Comment by xdh096** [comment]
> hi,Did you solve this problem and how it was solved? thanks!

**Comment by gmberton** [comment]
I think this issue happens if you download Aachen from visuallocalization.net
For this pipeline, you should download the dataset following the README here
https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/pipelines/Aachen_v1_1/README.md

**Comment by Skydes** [comment]
PR https://github.com/cvg/Hierarchical-Localization/pull/263 should fix the issue.
