### ISSUE TITLE
process Error in triangulation (died with <Signals.SIGKILL: 9>.)

### ISSUE THREAD

**Issue by rishabhramteke** [cvg/Hierarchical-Localization#153]
Got this error while running robotcar pipeline :
Traceback (most recent call last):
  File "pipe_test.py", line 78, in <module>
    triangulation.main(
  File "/home/ubuntu/Hierarchical-Localization/hloc/triangulation.py", line 181, in main
    stats = run_triangulation(
  File "/home/ubuntu/Hierarchical-Localization/hloc/triangulation.py", line 138, in run_triangulation
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['colmap', 'point_triangulator', '--database_path', 'outputs/robotcar_test/sfm_superpoint+superglue/database.db', '--image_path', 'datasets/robotcar_test/images', '--input_path', 'outputs/robotcar_test/sfm_superpoint+superglue/empty', '--output_path', 'outputs/robotcar_test/sfm_superpoint+superglue', '--Mapper.ba_refine_focal_length', '0', '--Mapper.ba_refine_principal_point', '0', '--Mapper.ba_refine_extra_params', '0']' died with <Signals.SIGKILL: 9>.

**Comment by Skydes** [comment]
Maybe your machine ran out of memory? Can you enable verbose with `verbose=True`?

**Comment by rishabhramteke** [comment]
Thank you for your response. In which .py file should I enable verbose ?

**Comment by rishabhramteke** [comment]
Thank you for your response. I will try debugging. 
Do you think there is any memory leakage in the trangulation code?

**Comment by Skydes** [comment]
`triangulation.main(..., verbose=True)`. No afaik there is no memory leak.

**Comment by rishabhramteke** [comment]
Traceback (most recent call last):
  File "pipe_test.py", line 75, in <module>
    triangulation.main(
TypeError: main() got an unexpected keyword argument 'verbose'

**Comment by rishabhramteke** [comment]
The code gets stuck during bundle adjustment
