### ISSUE TITLE
how can I get the .mat file 

### ISSUE THREAD

**Issue by fumenglin** [cvg/Hierarchical-Localization#211]
when runing pipeline_InLoc.ipynb code； get the issues like:
Traceback (most recent call last):
  File "/Users/fumenglin/PycharmProjects/Hierarchical-Localization/main.py", line 42, in <module>
    localize_inloc.main(
  File "/Users/fumenglin/PycharmProjects/Hierarchical-Localization/hloc/localize_inloc.py", line 137, in main
    ret, mkpq, mkpr, mkp3d, indices, num_matches = pose_from_cluster(
  File "/Users/fumenglin/PycharmProjects/Hierarchical-Localization/hloc/localize_inloc.py", line 87, in pose_from_cluster
    scan_r = loadmat(Path(dataset_dir, r + '.mat'))["XYZcut"]
  File "/Users/fumenglin/.conda/envs/pythonProject/lib/python3.8/site-packages/scipy/io/matlab/mio.py", line 216, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/Users/fumenglin/.conda/envs/pythonProject/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/fumenglin/.conda/envs/pythonProject/lib/python3.8/site-packages/scipy/io/matlab/mio.py", line 19, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/Users/fumenglin/.conda/envs/pythonProject/lib/python3.8/site-packages/scipy/io/matlab/mio.py", line 47, in _open_file
    raise IOError('Reader needs file name or open file-like object')
OSError: Reader needs file name or open file-like object

How Can I get the .mat file，thank you

**Comment by Skydes** [comment]
’.mat‘ files can be downloaded on the dataset website: http://www.ok.sc.e.titech.ac.jp/INLOC/subpages/inloc_db.html

**Comment by fumenglin** [comment]
Thank you so much for answering my question；
but this link is invalid ；when I wget like this:
2022-07-30 04:54:43 (0.00 B/s) - Connection closed at byte 0. Retrying.

--2022-07-30 04:54:53--  (try:18)  http://www.ok.sc.e.titech.ac.jp/INLOC/materials/scans.tar.gz
Connecting to www.ok.sc.e.titech.ac.jp (www.ok.sc.e.titech.ac.jp)|131.112.79.195|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 171509233098 (160G) [application/x-gzip]
Saving to: ‘scans.tar.gz.2’

scans.tar.gz.2               0%[                                      ]       0  --.-KB/s    in 0s      

2022-07-30 04:54:54 (0.00 B/s) - Connection closed at byte 0. Retrying.

--2022-07-30 04:55:04--  (try:19)  http://www.ok.sc.e.titech.ac.jp/INLOC/materials/scans.tar.gz
Connecting to www.ok.sc.e.titech.ac.jp (www.ok.sc.e.titech.ac.jp)|131.112.79.195|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 171509233098 (160G) [application/x-gzip]
Saving to: ‘scans.tar.gz.2’

scans.tar.gz.2               0%[                                      ]       0  --.-KB/s    in 0s      

2022-07-30 04:55:04 (0.00 B/s) - Connection closed at byte 0. Retrying.

--2022-07-30 04:55:14--  (try:20)  http://www.ok.sc.e.titech.ac.jp/INLOC/materials/scans.tar.gz
Connecting to www.ok.sc.e.titech.ac.jp (www.ok.sc.e.titech.ac.jp)|131.112.79.195|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 171509233098 (160G) [application/x-gzip]
Saving to: ‘scans.tar.gz.2’

scans.tar.gz.2               0%[                                      ]       0  --.-KB/s    in 0s      

2022-07-30 04:55:14 (0.00 B/s) - Connection closed at byte 0. Giving up

and  this vps in the US, California

Could you provide a mini sample of the completed input data? 
now I ignore the .mat file, like this       
  # scan_r = loadmat(Path(dataset_dir, r + '.mat'))["XYZcut"]

but other error  in code:

    path = Path(
        dataset_dir, 'database/alignments', floor_name,
        f'transformations/{building_name}_trans_{scan_id}.txt')
    with open(path) as f:
        raw_lines = f.readlines()
what the path file ?

thank you !

        scan_r = np.random.rand(height, width,10)
