### ISSUE TITLE
problem with netvlad

### ISSUE THREAD

**Issue by mrKornWij** [cvg/Hierarchical-Localization#223]
in retrieval part(using netvlad). I've got an error said 'could not read bytes'

**Comment by Skydes** [comment]
This error message is not sufficiently informative to help.

**Comment by silver-obelisk** [comment]
> This error message is not sufficiently informative to help.



> in retrieval part(using netvlad). I've got an error said 'could not read bytes'

Hi,I meet the same problem when I try to use netvlad. Did you solved it?  pairs_from_exhaustive is work, but sequential used netvlad doesnot work.


`/home/lv/anaconda3/envs/hl2/bin/python /home/lv/lab/HL/Hierarchical-Localization/SFM.py 
[2023/06/20 16:29:32 hloc INFO] Extracting local features with configuration:
{'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': -1}}
[2023/06/20 16:29:32 hloc INFO] Found 151 images in root datasets/tanks_and_temple/Horse/images.
Traceback (most recent call last):
  File "/home/lv/lab/HL/Hierarchical-Localization/SFM.py", line 42, in <module>
    retrieval_path = extract_features.main(retrieval_conf, images, outputs)
  File "/home/lv/anaconda3/envs/hl2/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/lv/lab/HL/Hierarchical-Localization/hloc/extract_features.py", line 251, in main
    model = Model(conf['model']).eval().to(device)
  File "/home/lv/lab/HL/Hierarchical-Localization/hloc/utils/base_model.py", line 17, in __init__
    self._init(conf)
  File "/home/lv/lab/HL/Hierarchical-Localization/hloc/extractors/netvlad.py", line 82, in _init
    mat = loadmat(checkpoint, struct_as_record=False, squeeze_me=True)
  File "/home/lv/anaconda3/envs/hl2/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 227, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/home/lv/anaconda3/envs/hl2/lib/python3.8/site-packages/scipy/io/matlab/_mio5.py", line 332, in get_variables
    res = self.read_var_array(hdr, process)
  File "/home/lv/anaconda3/envs/hl2/lib/python3.8/site-packages/scipy/io/matlab/_mio5.py", line 292, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "_mio5_utils.pyx", line 666, in scipy.io.matlab._mio5_utils.VarReader5.array_from_header
  File "_mio5_utils.pyx", line 713, in scipy.io.matlab._mio5_utils.VarReader5.array_from_header
  File "_mio5_utils.pyx", line 964, in scipy.io.matlab._mio5_utils.VarReader5.read_struct
  File "_mio5_utils.pyx", line 664, in scipy.io.matlab._mio5_utils.VarReader5.read_mi_matrix
  File "_mio5_utils.pyx", line 711, in scipy.io.matlab._mio5_utils.VarReader5.array_from_header
  File "_mio5_utils.pyx", line 884, in scipy.io.matlab._mio5_utils.VarReader5.read_cells
  File "_mio5_utils.pyx", line 664, in scipy.io.matlab._mio5_utils.VarReader5.read_mi_matrix
  File "_mio5_utils.pyx", line 713, in scipy.io.matlab._mio5_utils.VarReader5.array_from_header
  File "_mio5_utils.pyx", line 964, in scipy.io.matlab._mio5_utils.VarReader5.read_struct
  File "_mio5_utils.pyx", line 664, in scipy.io.matlab._mio5_utils.VarReader5.read_mi_matrix
  File "_mio5_utils.pyx", line 711, in scipy.io.matlab._mio5_utils.VarReader5.array_from_header
  File "_mio5_utils.pyx", line 884, in scipy.io.matlab._mio5_utils.VarReader5.read_cells
  File "_mio5_utils.pyx", line 664, in scipy.io.matlab._mio5_utils.VarReader5.read_mi_matrix
  File "_mio5_utils.pyx", line 695, in scipy.io.matlab._mio5_utils.VarReader5.array_from_header
  File "_mio5_utils.pyx", line 769, in scipy.io.matlab._mio5_utils.VarReader5.read_real_complex
  File "_mio5_utils.pyx", line 446, in scipy.io.matlab._mio5_utils.VarReader5.read_numeric
  File "_mio5_utils.pyx", line 351, in scipy.io.matlab._mio5_utils.VarReader5.read_element
  File "_streams.pyx", line 171, in scipy.io.matlab._streams.ZlibInputStream.read_string
  File "_streams.pyx", line 164, in scipy.io.matlab._streams.ZlibInputStream.read_into
OSError: could not read bytes

Process finished with exit code 1
`

**Comment by Skydes** [comment]
This means that the weights could not be successfully loaded, they should be downloaded from [here](https://cvg-data.inf.ethz.ch/hloc/netvlad/Pitts30K_struct.mat) to
```bash
python -c "import torch; print(f'{torch.hub.get_dir()}/netvlad/VGG16-NetVLAD-Pitts30K.mat')"
```

**Comment by YanAwithU** [comment]
I just encountered same problem, above solution works for me. Thanks!
