### ISSUE TITLE
pairs_from_retrieval

### ISSUE THREAD

**Issue by ceremaa** [cvg/Hierarchical-Localization#25]
Hello, 
Thank you for your great work.
I have a question about "pairs_from_retrieval.py". 
I would like to know please what exactly contains "--descriptors ", "--query_list" and "--db_list "?  
For example if I have one query image and n images in my database. Descriptors will be an h5 file containing the global descriptors of query images and n images in the database?
I did the same thing but I still have the following error 

Traceback (most recent call last):
  File "/gdrive/MyDrive/Hierarchical-Localization/hloc/pairs_from_retrieval.py", line 69, in <module>
    main(**args.__dict__)
  File "/gdrive/MyDrive/Hierarchical-Localization/hloc/pairs_from_retrieval.py", line 43, in main
    db_desc = tensor_from_names(db_names)
  File "/gdrive/MyDrive/Hierarchical-Localization/hloc/pairs_from_retrieval.py", line 39, in tensor_from_names
    desc = [hfile[i]['global_descriptor'].__array__() for i in names]
  File "/gdrive/MyDrive/Hierarchical-Localization/hloc/pairs_from_retrieval.py", line 39, in <listcomp>
    desc = [hfile[i]['global_descriptor'].__array__() for i in names]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/dataset.py", line 506, in __getitem__
    new_dtype = readtime_dtype(self.id.dtype, names)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/dataset.py", line 48, in readtime_dtype
    raise ValueError("Field names only allowed for compound types")
ValueError: Field names only allowed for compound types

I use https://github.com/yxgeee/OpenIBL to Extract descriptor then i save it to h5 file

**Comment by Skydes** [comment]
Hi,
I am actually planning to integrate OpenIBL at some point but haven't tried it out yet :)

`--descriptors` is a path to a HDF5 file, as described [here](https://github.com/cvg/Hierarchical-Localization#using-your-own-image-retrieval). You can create it the following commands:
```python
with h5py.File(path, 'a') as hfile:
    grp = hfile.create_group(image_name)
    grp.create_dataset('global_descriptor', data=desc)
```

Next, the script needs to know which entries in this HDF5 file are queries or reference images. Two solutions:
- if the name of query and ref images have different prefixes (e.g. they are in different subfolders), you can provide them with `--query_prefix` and `--db_prefix` (that's the easiest option)
- you can provide lists of query and ref images in different text files using `--query_list` and `--db_list`. For now they also need intrinsics (possibly faked) and will be parsed by [this function](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/utils/parsers.py#L7), but it would be easy to modify the code to just read image names.

Your error probably comes from incorrect image names (e.g. tuples) - we should add checks to prevent this.

**Comment by ceremaa** [comment]
**Thank you very much for this answer.**
I have a question about the localization  on costum dataset. Should I organize the images as follows?

1. newdatabase
2.        images
     3.         db
     3.         query

Then I apply the same steps in pipeline_SfM.ipynb
Then to locate the query images :
1. Match the query images
match_features.main(matcher_conf, loc_pairs, feature_conf['output'], outputs)
2.Localize
localize_sfm.main(...)
   
But I still had the same error in the last localization step 
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: 'Unable to open object (component not found)'

Are the steps correct to localize new image in costum dataset ?
**Thank you very much**

**Comment by Skydes** [comment]
At what line and file is the error raised? The steps look correct but I suspect that there is a problem with image names. 
- if you called `extract_features` on `images/`, then the matching in `pipeline_SfM` cannot be exhaustive and you need to provide an explicit list of pairs (otherwise it would run SfM on the queries as well). Then `pairs_from_retrieval` can be run with the prefixes.
- if you called `extract_features` two times, first on `images/db/` and then on `images/query/`, then the image names do not have the `db/` and `query/` prefixes, and you most likely cannot run `pairs_from_retrieval` with prefixes.

I suggest that you put your images in two directories `images_db/db/` and `images_query/query/`, first run SfM on `images_db/`, then localize images in `images_query/` using the prefixes `db` and `query` for `pairs_from_retrieval`.

**Comment by ceremaa** [comment]
Thank you very much that helped me a lot.
1. Could you please tell me how (in which function) I can change the camera model before extract_features?
2. can I use colmap for 3D reconstruction and then apply your localization steps?
 thank you very much for your time

**Comment by half-potato** [comment]
You can look at my branch for an example of how to perform image retrieval. The example is in pipeline_SfM.ipynb.
https://github.com/half-potato/Hierarchical-Localization/tree/robotcar

**Comment by Skydes** [comment]
Closing this issue due to inactivity. Feel free to reopen it.

**Comment by tudipffmgt** [comment]
I am facing a similar issue. I want to run the pipeline_Aachen under Ubuntu 20.04.
My data is structured as follows:
```
/datasets/my_dataset/images/db
/datasets/my_dataset/images/query
/pairs/my_dataset/pairs_from_my_own_retrieval.txt
/outputs/my_dataset/my_COLMAP_model/*.bin
```

I run 

```
from pathlib import Path
from pprint import pformat

from hloc import extract_features, match_features, pairs_from_covisibility
from hloc import colmap_from_nvm, triangulation, localize_sfm, visualization

dataset = Path('datasets/my_dataset/')  # change this if your dataset is somewhere else
images = dataset / 'images/'

pairs = Path('pairs/my_dataset/')
sfm_pairs = pairs / 'pairs-db-covis20.txt'  # top 20 most covisible in SIFT model not needed as model is already generated?
loc_pairs = pairs / 'pairs_from_my_own_retrieval.txt'  # top 50 retrieved by my own retrieval

outputs = Path('outputs/my_dataset/')  # where everything will be saved
reference_sfm = outputs / 'sfm_superpoint+superglue'  # the SfM model we will build
results = outputs / 'my_dataset_hloc_superpoint+superglue_retrieval20.txt'  # the result file

# list the standard configurations available
print(f'Configs for feature extractors:\n{pformat(extract_features.confs)}')
print(f'Configs for feature matchers:\n{pformat(match_features.confs)}')

feature_conf = extract_features.confs['superpoint_aachen']
matcher_conf = match_features.confs['superglue']

feature_path = extract_features.main(feature_conf, images, outputs)

pairs_from_covisibility.main(
    outputs / 'TBP_superglue', sfm_pairs, num_matched=20)
    
print(sfm_pairs)
    
sfm_match_path = match_features.main(matcher_conf, sfm_pairs, feature_conf['output'], outputs)
```
I get the error
`KeyError: "Unable to open object (object 'df_hauptkatalog_0129217.jpg' doesn't exist)"`
and when I check the generated pairs-db-covis20.txt I can see that no db/ or query/ is added in front of my images as for the Aachen example dataset. How would I fix this?
The first line is e.g., df_hauptkatalog_0129217.jpg df_hauptkatalog_0105612.jpg but the images are in /db/df_hauptkatalog_0129217.jpg

For a workaround I try inserting it into `pairs_from_covisibility.py` line 50.
