### ISSUE TITLE
Has anyone actually installed on Windows?

### ISSUE THREAD

**Issue by antithing** [cvg/Hierarchical-Localization#276]
I see a few threads about this, but there seems to be no resolution. (pycolmap cannot be installed)

If you have built on Windows, please share your steps!

Thank you!

**Comment by MHz777** [comment]
I have installed hloc and pycolmap in windows10 with condd-forge ,but it is not work. 
that is the error:
**Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\ns\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\ns\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\ns\Scripts\ns-process-data.exe\__main__.py", line 4, in <module>
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\nerfstudio\scripts\process_data.py", line 36, in <module>
    from nerfstudio.process_data.colmap_converter_to_nerfstudio_dataset import (
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\nerfstudio\process_data\colmap_converter_to_nerfstudio_dataset.py", line 21, in <module>
    from nerfstudio.process_data import colmap_utils, hloc_utils, process_data_utils
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\nerfstudio\process_data\hloc_utils.py", line 32, in <module>
    from hloc import (
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\hloc\__init__.py", line 24, in <module>
    found_version = version.parse(getattr(pycolmap, '__version__'))
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\packaging\version.py", line 52, in parse
    return Version(version)
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\packaging\version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'dev'
(ns) PS E:\Nerfprojc\Hierarchical-Localization> ns-process-data
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\ns\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\ns\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\ns\Scripts\ns-process-data.exe\__main__.py", line 4, in <module>
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\nerfstudio\scripts\process_data.py", line 36, in <module>
    from nerfstudio.process_data.colmap_converter_to_nerfstudio_dataset import (
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\nerfstudio\process_data\colmap_converter_to_nerfstudio_dataset.py", line 21, in <module>
    from nerfstudio.process_data import colmap_utils, hloc_utils, process_data_utils
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\nerfstudio\process_data\hloc_utils.py", line 32, in <module>
    from hloc import (
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\hloc\__init__.py", line 24, in <module>
    found_version = version.parse(getattr(pycolmap, '__version__'))
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\packaging\version.py", line 52, in parse
    return Version(version)
  File "C:\ProgramData\anaconda3\envs\ns\lib\site-packages\packaging\version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'dev'**

**Comment by greenbrettmichael** [comment]
conda install pycolmap instead of pip install pycolmap resolved the issue for me on the latest hloc code. not the greatest solution.

**Comment by MHz777** [comment]
感谢您的回复，期待更加深入的交流
