### ISSUE TITLE
Aachen dataset running issue "Invalid HDF5 object reference"

### ISSUE THREAD

**Issue by snowzhangy** [cvg/Hierarchical-Localization#28]
hello:
    Could you help me to check if I missed something? I'm trying to reproduce the Aachen dataset result. I tried both 1.1 and original one. They both failed at the same step. (all step above runs fine).
I'm running from windows 10 x64 bit. cuda 11 on 3090 card.
here is the log.
thank you so much

KeyError                                  Traceback (most recent call last)
<ipython-input-8-2c77fffe3840> in <module>
----> 1 sfm_match_path = match_features.main(matcher_conf, sfm_pairs, feature_conf['output'], outputs)

c:\users\cinetec\appdata\local\programs\python\python37\lib\site-packages\torch\autograd\grad_mode.py in decorate_context(*args, **kwargs)
     24         def decorate_context(*args, **kwargs):
     25             with self.__class__():
---> 26                 return func(*args, **kwargs)
     27         return cast(F, decorate_context)
     28 

F:\temp\slam\superglue\Hierarchical-Localization\hloc\match_features.py in main(conf, pairs, features, export_dir, exhaustive)
     89         print(name0)
     90         print(name1)
---> 91         feats0, feats1 = feature_file[name0], feature_file[name1]
     92         for k in feats1.keys():
     93             data[k+'0'] = feats0[k].__array__()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

c:\users\cinetec\appdata\local\programs\python\python37\lib\site-packages\h5py\_hl\group.py in __getitem__(self, name)
    262                 raise ValueError("Invalid HDF5 object reference")
    263         else:
--> 264             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    265 
    266         otype = h5i.get_type(oid)

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5o.pyx in h5py.h5o.open()

KeyError: 'Unable to open object (component not found)'

**Comment by Skydes** [comment]
I have never ran hloc on Windows so a crash is not unsurprising. The pair lists that I provide use UNIX-style paths with a '/' separator. For Windows you should edit these files to use the '\' separator. Exporting the results in localize_sfm.py will also break. It might also crash elsewhere.

**Comment by snowzhangy** [comment]
> I have never ran hloc on Windows so a crash is not unsurprising. The pair lists that I provide use UNIX-style paths with a '/' separator. For Windows you should edit these files to use the '' separator. Exporting the results in localize_sfm.py will also break. It might also crash elsewhere.

Hi Skydes:
    Thank you for your answer. I just tried run this script on ubuntu for the aachen v1.1 dataset. still exact same error at the same location. any idea?
thank you

**Comment by Skydes** [comment]
Does it crash elsewhere? Or is updating the pair file sufficient? Did you need to apply the changes of PR https://github.com/cvg/Hierarchical-Localization/pull/29?

**Comment by snowzhangy** [comment]
> Does it crash elsewhere? Or is updating the pair file sufficient? Did you need to apply the changes of PR #29?
Hi Skydes. it seams aachen 1.1 dataset still crash. I guess the generated data and the path still conflict on windows.
trying the original 1.0 dataset now. will keep you update.

**Comment by Skydes** [comment]
Closing this issue due to inactivity. Feel free to reopen it.

**Comment by ssssjiang** [comment]
I also encountered a similar problem, but I was running in docker and the system was ubuntu 16

> Loaded SuperGlue model ("outdoor" weights)
  0%|          | 0/133066 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/persist/Hierarchical-Localization/venv/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/persist/Hierarchical-Localization/hloc/match_features.py", line 138, in match_from_paths
    grp = fd[name0]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/persist/Hierarchical-Localization/venv/lib/python3.6/site-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)

**Comment by Skydes** [comment]
1. Could you please copy the entire traceback with the exception?
2. Did you make sure that the feature extraction ran smoothly beforehand?
3. Could you please catch the exception and print the requested key vs the keys contained in the hdf5 feature file? `hloc.utils.io.list_h5_names` might be helpful.

**Comment by ssssjiang** [comment]
> 1. Could you please copy the entire traceback with the exception?
> 2. Did you make sure that the feature extraction ran smoothly beforehand?
> 3. Could you please catch the exception and print the requested key vs the keys contained in the hdf5 feature file? `hloc.utils.io.list_h5_names` might be helpful.

Thank you for your answer.I have just solved this problem. This problem has nothing to do with the code，thank you.

**Comment by Allencheng97** [comment]
> > 1. Could you please copy the entire traceback with the exception?
> > 2. Did you make sure that the feature extraction ran smoothly beforehand?
> > 3. Could you please catch the exception and print the requested key vs the keys contained in the hdf5 feature file? `hloc.utils.io.list_h5_names` might be helpful.
> 
> Thank you for your answer.I have just solved this problem. This problem has nothing to do with the code，thank you.

Hi, Can you provide the solution to this problem? I have the same issue but I don't know which part is wrong. Thank you!

**Comment by salt0107fish** [comment]
> > > 1. Could you please copy the entire traceback with the exception?
> > > 2. Did you make sure that the feature extraction ran smoothly beforehand?
> > > 3. Could you please catch the exception and print the requested key vs the keys contained in the hdf5 feature file? `hloc.utils.io.list_h5_names` might be helpful.
> > 
> > 
> > Thank you for your answer.I have just solved this problem. This problem has nothing to do with the code，thank you.
> 
> Hi, Can you provide the solution to this problem? I have the same issue but I don't know which part is wrong. Thank you!

Have you solved this problem? I met the same issue...I guess the data format maybe wrong, but I can't solve it! Could you help me?

**Comment by feifeiwei** [comment]
i sloved this problem by changing aachen data with aachen_v1_1 dataset...
