### ISSUE TITLE
triangulation faiied

### ISSUE THREAD

**Issue by kaiyi98** [cvg/Hierarchical-Localization#297]
hello！
I use hloc to my dataset，but failed in triangulation. I don't understand why this error occurs.

`[2023/07/25 16:12:52 hloc INFO] Running 3D triangulation...
[2023/07/25 16:12:55 hloc ERROR] Failed with output:

==============================================================================
Loading database
==============================================================================

Loading cameras... 1 in 0.003s
Loading matches... 12630 in 0.524s
Loading images... 642 in 1.009s (connected 642)
Building correspondence graph... in 0.430s (ignored 0)

Traceback (most recent call last):
  File "/home/root/anaconda3/envs/hloc/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/root/anaconda3/envs/hloc/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/root/zfl/Hierarchical-Localization/hloc/pipelines/ParkingLot/pipeline.py", line 62, in <module>
    triangulation.main(
  File "/home/root/zfl/Hierarchical-Localization/hloc/triangulation.py", line 232, in main
    reconstruction = run_triangulation(sfm_dir, database, image_dir, reference,
  File "/home/root/zfl/Hierarchical-Localization/hloc/triangulation.py", line 194, in run_triangulation
    reconstruction = pycolmap.triangulate_points(
IndexError: _Map_base::at`

**Comment by kaiyi98** [comment]
I have solved it!

**Comment by cameronosmith** [comment]
How did you solve it? Same problem here

**Comment by linhanwang** [comment]
> How did you solve it? Same problem here

https://github.com/colmap/pycolmap/issues/116
