### ISSUE TITLE
Triangulation Failed

### ISSUE THREAD

**Issue by monamourvert** [cvg/Hierarchical-Localization#311]
Hi, thanks for the amazing work. I just tried your code to relocalize my own dataset. But somehow, I found an error when I  performed the matcher. 

Here is what I did:
1. I have 3D map (cameras.bin, images.bin, and points3D.bin) retrieved from the Colmap. Later, I'll use this reference model to triangulate the new SfM model
2. I extract the features for all database and queries, then perform pairs_from_covisibilty. It worked
3. Moved to the matches, I got this issue:

```
Loaded SuperPoint model
100%|██████████████████████████████████████████████████████████████████| 2210/2210 [01:13<00:00, 29.98it/s]
[2023/09/27 13:48:00 hloc INFO] Finished exporting features.
[2023/09/27 13:48:00 hloc INFO] Reading the COLMAP model...
[2023/09/27 13:48:02 hloc.utils.read_write_model WARNING] This SfM file structure was deprecated in hloc v1.1
[2023/09/27 13:48:02 hloc INFO] Extracting image pairs from covisibility info...
100%|█████████████████████████████████████████████████████████████████| 1105/1105 [00:01<00:00, 624.03it/s]
[2023/09/27 13:48:04 hloc INFO] Found 11050 pairs.
[2023/09/27 13:48:04 hloc INFO] Matching local features with configuration:
{'model': {'name': 'superglue',
           'sinkhorn_iterations': 50,
           'weights': 'outdoor'},
 'output': 'matches-superglue'}
Loaded SuperGlue model ("outdoor" weights)
  0%|                                                                             | 0/6360 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "./dev/Hierarchical-Localization/hloc/pipelines/library/db5.py", line 31, in <module>
    sfm_matches = match_features.main(matcher_conf,sfm_pair,feature_conf['output'],outputs) #matches from sfm model
  File "/home/nanda/dev/Hierarchical-Localization/hloc/match_features.py", line 160, in main
    match_from_paths(conf, pairs, matches, features_q, features_ref, overwrite)
  File "/home/nanda/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/nanda/dev/Hierarchical-Localization/hloc/match_features.py", line 219, in match_from_paths
    for idx, data in enumerate(tqdm(loader, smoothing=.1)):
  File "/home/nanda/.local/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/nanda/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/nanda/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/nanda/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/nanda/.local/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/nanda/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/nanda/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nanda/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nanda/dev/Hierarchical-Localization/hloc/match_features.py", line 108, in __getitem__
    grp = fd[name0]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/nanda/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'frame000074.png' doesn't exist)"
```

Would you enlighten me why this happened? And I also curious about the warning of my SfM model reference. Is that also affected the whole code? Thank you!

**Comment by monamourvert** [comment]
Update, the error above because something's wrong with my prefix. But now it failed on the triangulation process as follows:

```
100%|███████████████████████████████████████████████████████████████| 1105/1105 [00:00<00:00, 59633.38it/s]
[2023/09/27 14:47:33 hloc INFO] Importing matches into the database...
100%|██████████████████████████████████████████████████████████████| 11050/11050 [00:02<00:00, 4029.93it/s]
[2023/09/27 14:47:36 hloc INFO] Performing geometric verification of the matches...
100%|██████████████████████████████████████████████████████████████████| 1105/1105 [00:47<00:00, 23.23it/s]
[2023/09/27 14:48:24 hloc INFO] mean/med/min/max valid matches 80.08/87.01/7.06/100.00%.
[2023/09/27 14:48:24 hloc INFO] Running 3D triangulation...
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0927 14:48:24.215937 73566 database.cc:85] Keypoint format not supported
*** Check failure stack trace: ***
Aborted (core dumped)

```
So, is it valid if the error above is correlated with my 3D model?

**Comment by sarlinpe** [comment]
Try deleting whatever is in your SfM folder and running the triangulation step again. For some reason the database seems corrupted.

**Comment by monamourvert** [comment]
I tried your advice and it produced the same error. Seems like there is something wrong in the geometric verification process. To check it, I tried to only perform the feature extractor and and image matching and exported that into a database. And it ended like this:

```
100%|████████████████████████████████████| 1105/1105 [00:00<00:00, 85157.67it/s]
[2023/10/03 16:24:22 hloc INFO] Importing matches into the database...
100%|█████████████████████████████████████| 9900/9900 [00:03<00:00, 2619.60it/s]
[2023/10/03 16:24:26 hloc INFO] Performing geometric verification of the matches...
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1003 16:24:26.196774 19814 database.cc:85] Keypoint format not supported
*** Check failure stack trace: ***
Aborted (core dumped)
```

And can you provide me more about the information of  corrupted database? I still don't get it why it related to the keypoint format etc. Thanks!

**Comment by monamourvert** [comment]
Solved this error by remove all repo and build it again from the scratch. I'll close this issue~
