### ISSUE TITLE
Reading pairs.txt breaks when filenames contain spaces

### ISSUE THREAD

**Issue by expenses** [cvg/Hierarchical-Localization#319]
Because `pairs.txt` uses space as a delimiter, any unix filenames that contain spaces will break it:
```
Traceback (most recent call last):
  File "/home/ashley/Hierarchical-Localization/process.py", line 46, in <module>
    match_features.main(matcher_conf, pairs, features=features, matches=matches)
  File "/home/ashley/Hierarchical-Localization/hloc/match_features.py", line 174, in main
    match_from_paths(conf, pairs, matches, features_q, features_ref, overwrite)
  File "/home/ashley/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ashley/Hierarchical-Localization/hloc/match_features.py", line 217, in match_from_paths
    pairs = parse_retrieval(pairs_path)
  File "/home/ashley/Hierarchical-Localization/hloc/utils/parsers.py", line 46, in parse_retrieval
    q, r = p.split()
ValueError: too many values to unpack (expected 2)
```

**Comment by sarlinpe** [comment]
Yes this is expected. We could use comma separators instead.

**Comment by isolin** [comment]
I just bumped into the same issue. It would be great to resolve it. Sounds like an easy but breaking change, unfortunately.
