### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'replace'

### ISSUE THREAD

**Issue by clousy188** [cvg/Hierarchical-Localization#365]
![image](https://github.com/cvg/Hierarchical-Localization/assets/130050060/f4aa6240-f6a8-4437-ae55-55d7a614e7ff)

**Comment by sarlinpe** [comment]
Please provide the code that resulted in the error. `holc_way.py` is not part of this repository.

**Comment by XushaopengHNU** [comment]
_**I'm getting the same bug, this is the completed error code, the screenshot is the error code and the contents of the loc_pairs.txt.**_
<img width="854" alt="error code" src="https://github.com/user-attachments/assets/05155e46-b9ee-4c65-ad8b-bb6406c77636" />
![loc_pairs](https://github.com/user-attachments/assets/c3539536-b66e-4df1-8312-cf26780986c1)

[2024/12/15 21:00:30 hloc INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-rmax1600',
 'preprocessing': {'grayscale': True, 'resize_force': True, 'resize_max': 1600}}
[2024/12/15 21:00:30 hloc INFO] Found 4 images in root F:\OneDrivePersonal\OneDrive\6-Dataset_code\9-Homography\Hierarchical-Localization\images.
[2024/12/15 21:00:30 hloc INFO] Skipping the extraction.
[2024/12/15 21:00:30 hloc INFO] Matching local features with configuration:
{'model': {'name': 'superglue',
           'sinkhorn_iterations': 50,
           'weights': 'outdoor'},
 'output': 'matches-superglue'}
Loaded SuperGlue model ("outdoor" weights)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.57s/it]
[2024/12/15 21:00:38 hloc INFO] Finished exporting matches.
time: 7.655455827713013
  0%|                                                                                                                               | 0/1 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "test4.py", line 44, in <module>
    matches,_ = get_matches(loc_matches, img1, img2name)
  File "F:\OneDrivePersonal\OneDrive\6-Dataset_code\9-Homography\Hierarchical-Localization\hloc\utils\io.py", line 70, in get_matches
    pair, reverse = find_pair(hfile, name0, name1)
  File "F:\OneDrivePersonal\OneDrive\6-Dataset_code\9-Homography\Hierarchical-Localization\hloc\utils\io.py", line 49, in find_pair
    pair = names_to_pair(name0, name1)
  File "F:\OneDrivePersonal\OneDrive\6-Dataset_code\9-Homography\Hierarchical-Localization\hloc\utils\parsers.py", line 55, in names_to_pair
    return separator.join((name0.replace("/", "-"), name1.replace("/", "-")))
AttributeError: 'numpy.ndarray' object has no attribute 'replace'
