### ISSUE TITLE
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)

### ISSUE THREAD

**Issue by tudipffmgt** [cvg/Hierarchical-Localization#40]
Hi, 

thank you for your amazing work. I have already been using SuperGlue for previous work. Now I wanted to test your workflow for my own images and wrote a litte script based on the `pipeline_SfM.ipynb`.
The script run_pipeline.py throws an error at `extract_features.main(feature_conf, images, outputs)` and looks like this:

```
from pathlib import Path

from hloc import extract_features, match_features, reconstruction, visualization

images = Path('images/')

outputs = Path('outputs/sfm/')
sfm_pairs = outputs / 'pairs-exhaustive.txt'  # exhaustive matching
sfm_dir = outputs / 'sfm_superpoint+superglue'

feature_conf = extract_features.confs['superpoint_aachen']
matcher_conf = match_features.confs['superglue']

features = feature_conf['output']
feature_file = f"{features}.h5"
match_file = f"{features}_{matcher_conf['output']}_{sfm_pairs.stem}.h5"

extract_features.main(feature_conf, images, outputs)
```

As an error message I get:
```
[01/25/2021 17:13:40 INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-r1024',
 'preprocessing': {'grayscale': True, 'resize_max': 1024}}
C:\Prg\anaconda3\envs\hloc\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Loaded SuperPoint model
[01/25/2021 17:13:40 INFO] Found 26 images in root images.
  0%|                                                                                           | 0/26 [00:00<?, ?it/s][01/25/2021 17:13:42 INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-r1024',
 'preprocessing': {'grayscale': True, 'resize_max': 1024}}
C:\Prg\anaconda3\envs\hloc\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Loaded SuperPoint model
[01/25/2021 17:13:42 INFO] Found 26 images in root images.
Traceback (most recent call last):
  File "C:\Prg\anaconda3\envs\hloc\lib\site-packages\h5py\_hl\files.py", line 185, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Prg\anaconda3\envs\hloc\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Prg\anaconda3\envs\hloc\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Prg\anaconda3\envs\hloc\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Prg\anaconda3\envs\hloc\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Prg\anaconda3\envs\hloc\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Prg\anaconda3\envs\hloc\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Prg\anaconda3\envs\hloc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Arbeit\Workspace\Hierarchical-Localization-master\run_pipeline.py", line 21, in <module>
    extract_features.main(feature_conf, images, outputs)
  File "C:\Prg\anaconda3\envs\hloc\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\Arbeit\Workspace\Hierarchical-Localization-master\hloc\extract_features.py", line 135, in main
    feature_file = h5py.File(str(feature_path), 'a')
  File "C:\Prg\anaconda3\envs\hloc\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\Prg\anaconda3\envs\hloc\lib\site-packages\h5py\_hl\files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'outputs\sfm\feats-superpoint-n4096-r1024.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = 502)
  0%|                                                                                           | 0/26 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "C:\Prg\anaconda3\envs\hloc\lib\site-packages\torch\utils\data\dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Prg\anaconda3\envs\hloc\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_pipeline.py", line 21, in <module>
    extract_features.main(feature_conf, images, outputs)
  File "C:\Prg\anaconda3\envs\hloc\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\Arbeit\Workspace\Hierarchical-Localization-master\hloc\extract_features.py", line 137, in main
    for data in tqdm(loader):
  File "C:\Prg\anaconda3\envs\hloc\lib\site-packages\tqdm\std.py", line 1167, in __iter__
    for obj in iterable:
  File "C:\Prg\anaconda3\envs\hloc\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Prg\anaconda3\envs\hloc\lib\site-packages\torch\utils\data\dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "C:\Prg\anaconda3\envs\hloc\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "C:\Prg\anaconda3\envs\hloc\lib\site-packages\torch\utils\data\dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 17152) exited unexpectedly
```
Is it because I am not using CUDA but I already used SuperGlue without CUDA or am I missing something else? The  .h5 is always created with 1 kb but seems like it cannot be opened. I am running the code on Windows 10. Thanks for any help :)

**Comment by Skydes** [comment]
Feature extraction should work well on CPU, but I have not tried on Windows. Did you try deleting the feature file and running the script again? Currently, it appears that the h5 file is corrupted if the extraction crashes.

**Comment by tudipffmgt** [comment]
Yes, I tried deleting only the file as well as deleting the whole folder structure. The error always reappears. I could try to reproduce this on a different machine but I would have to set up all the files at first.

**Comment by Skydes** [comment]
Could you pinpoint where this crashes using a debugger? It's unclear at what line does h5py throw an error.

**Comment by tudipffmgt** [comment]
I tried debugging using pdb. This is the output until the first error occurs: 
```
-> extract_features.main(feature_conf, images, outputs)
(Pdb) n
[01/26/2021 10:22:07 INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-r1024',
 'preprocessing': {'grayscale': True, 'resize_max': 1024}}
C:\Prg\anaconda3\envs\hloc\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Loaded SuperPoint model
[01/26/2021 10:22:07 INFO] Found 26 images in root images.
  0%|                                                                                           | 0/26 [00:00<?, ?it/s]> c:\arbeit\workspace\hierarchical-localization-master\run_pipeline.py(21)<module>()
-> extract_features.main(feature_conf, images, outputs)
(Pdb) n
[01/26/2021 10:22:18 INFO] Extracting local features with configuration:
{'model': {'max_keypoints': 4096, 'name': 'superpoint', 'nms_radius': 3},
 'output': 'feats-superpoint-n4096-r1024',
 'preprocessing': {'grayscale': True, 'resize_max': 1024}}
C:\Prg\anaconda3\envs\hloc\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Loaded SuperPoint model
[01/26/2021 10:22:18 INFO] Found 26 images in root images.
OSError: Unable to create file (unable to open file: name = 'outputs\sfm\feats-superpoint-n4096-r1024.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = 502)
> c:\arbeit\workspace\hierarchical-localization-master\run_pipeline.py(21)<module>()
-> extract_features.main(feature_conf, images, outputs)
```
At this point the file 'feats-superpoint-n4096-r1024.h5' was already created in outputs\sfm\. Maybe a problem with setting the path in Windows 10? I already tried using absolute paths for the dataset. I also tried using the provided South-Building dataset and ran into the same error.

**Comment by tudipffmgt** [comment]
This could be the same error: https://github.com/h5py/h5py/issues/1090

**Comment by Skydes** [comment]
I unfortunately don't have access to a Windows machine to try to reproduce the error. The pdb trace is too coarse, you would need to check what's happening in `extract_features`.

**Comment by tudipffmgt** [comment]
Sorry for the late reply. At the moment I was not able to fix the issue but I am using a jupyter notebook now and it works for my purpose. Thanks anyway :)
