### ISSUE TITLE
Issue while Performing Geometric Verification

### ISSUE THREAD

**Issue by paidiakileswar** [cvg/Hierarchical-Localization#431]
Hai @everyone ->

Can you please do help me here -> I was trying to add 

Superpoint + Sphereglue -> In the middle I am stuck here
Sphereglue -> https://github.com/vishalsharbidar/SphereGlue.git

While i am running pycolmap.verify_matches()

I am getting issue , I stuck here , I cant move forward from past 5 days

![image](https://github.com/user-attachments/assets/0c43b11e-e75a-465e-be50-756280f5045d)

Output ->
![image](https://github.com/user-attachments/assets/fc6f0f7e-3e73-4781-971a-2ab86322e073)

This is gdb Backtrace 

```
(gdb) backtrace

  #0  0x00007ffff5ccc0eb in colmap::TwoViewGeometry::EstimateUncalibrated(colmap::Camera const&, std::vector<Eigen::Matrix<double, 2, 1, 0, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1, 0, 2, 1> > > const&, colmap::Camera const&, std::vector<Eigen::Matrix<double, 2, 1, 0, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1, 0, 2, 1> > > const&, std::vector<colmap::FeatureMatch, std::allocator<colmap::FeatureMatch> > const&, colmap::TwoViewGeometry::Options const&) ()
   from /home/ubuntu/conda/envs/pixsfm/lib/python3.8/site-packages/pycolmap.cpython-38-x86_64-linux-gnu.so
#1  0x00007ffff5d0ab7c in colmap::TwoViewGeometryVerifier::Run() () from /home/ubuntu/conda/envs/pixsfm/lib/python3.8/site-packages/pycolmap.cpython-38-x86_64-linux-gnu.so
#2  0x00007ffff5e35111 in colmap::Thread::RunFunc() () from /home/ubuntu/conda/envs/pixsfm/lib/python3.8/site-packages/pycolmap.cpython-38-x86_64-linux-gnu.so
#3  0x00007fffda892793 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7f90609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007ffff7d5b353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Can anyone Why this is occuring , Where I am going Wrong..

@pyetras @rAm1n @jobesu14 @humenbergerm @scott-vsi

**Comment by paidiakileswar** [comment]
Resolved -> Issue is Mismatch in size between the features & Matches
