### ISSUE TITLE
can the superpoint model in pipeline_aachen be used in HF-Net Localization?

### ISSUE THREAD

**Issue by happybored** [cvg/Hierarchical-Localization#64]
hello,
I use "triangulation.main" to generate colmap model,then use it to run ''python3 hfnet/evaluate_aachen.py"
but it gets error while starting evaluation.
`[04/15/2021 02:56:42 INFO] Starting evaluation
  0%|                                                                                                                                          | 0/824 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "hfnet/evaluate_aachen.py", line 137, in <module>
    loc, queries, query_dataset, max_iter=args.max_iter)
  File "/root/hfnet/hfnet/evaluation/localization.py", line 216, in evaluate
    result, stats = loc.localize(query_info, query_data, debug=False)
  File "/root/hfnet/hfnet/evaluation/localization.py", line 147, in localize
    prior_ids, self.local_db, self.points)
  File "/root/hfnet/hfnet/evaluation/utils/localization.py", line 73, in covis_clustering
    connected_frames = set(i for lm in landmarks
  File "/root/hfnet/hfnet/evaluation/utils/localization.py", line 74, in <genexpr>
    for i in points[lm].image_ids)
KeyError: 1127994`
what's wrong ?

**Comment by Skydes** [comment]
Hi,
hloc and hfnet are different pipelines and ensuring cross-compatibility would be too complicated. The HF-Net pipeline is deprecated and hloc should be used instead.
